version: "3.8"

networks:
  proxy-net:
    external: true

services:
  dummy-web:
    image: nginx:alpine
    container_name: dummy-web
    restart: unless-stopped
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dummy.rule=Host(`crm.jordazola.com`)"
      - "traefik.http.routers.dummy.entrypoints=web"
