version: "3.8"

networks:
  proxy-net:
    external: true

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme:/acme
      - ./config:/config
    command:
      # Logs
      - "--log.level=INFO"

      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # Redirección global HTTP -> HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

      # Docker Provider
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      # File Provider
      - "--providers.file.directory=/config"
      - "--providers.file.watch=true"

      # Let's Encrypt (Certificados automáticos)
      - "--certificatesresolvers.le.acme.email=gerencia@sotodelprior.com"
      - "--certificatesresolvers.le.acme.storage=/acme/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"

      # Configurar 'le' como el resolver por defecto para HTTPS
      - "--entrypoints.websecure.http.tls.certResolver=le"

    networks:
      - proxy-net
